---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.5"
  #  matchLabels:
  #    app: mongo-c # has to match .spec.template.metadata.labels
  security:
    authentication:
      modes:
        - SCRAM
  users:
    - name: {{.Values.db.adminname}}
      db: {{.Values.db.admindb}}
      passwordSecretRef:
        name: {{.Values.name}}-admin-secret
      roles:
        - name: clusterAdmin
          db: {{.Values.db.admindb}}
        - name: "readWrite"
          db: {{.Values.db.admindb}}
        - name: userAdminAnyDatabase
          db: {{.Values.db.admindb}}
      scramCredentialsSecretName: my-scram
    - name: {{.Values.db.username}}
      db: {{.Values.db.userdb}}
      passwordSecretRef:
        name: {{.Values.name}}-user-secret
      roles:
#        - name: clusterAdmin
#          db: Archimedes-Rest
        - name: "readWrite"
          db: {{.Values.db.userdb}}
#        - name: userAdminAnyDatabase
#          db: Archimedes-Rest
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "1"
                  memory: 2Gi
                requests:
                  cpu: 500m
                  memory: 1Gi
            - name: mongo-exporter
              image: bitnami/mongodb-exporter:latest
              ports:
                - containerPort: {{.Values.metrics.port}}
                  name: mongo-metrics
              args:
                [
                  "--mongodb.uri=mongodb://127.0.0.1:27017/",
                  "--web.listen-address=:9216",
                ]
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - my-mongodb
                  topologyKey: "kubernetes.io/hostname"
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 40G
