---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-admin-secret
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  password: {{.Values.secret.adminpassword}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-user-secret
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  password: {{.Values.secret.userpassword}}