#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: mongo-metrics
#  labels:
#    app: mongo-metrics
#spec:
#  selector:
#    app: mongo
#  ports:
#    - protocol: TCP
#      port: 9216
#      name: metrics
#      targetPort: 9216

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongo
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mongo-metrics
  endpoints:
    - port: mongo-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongo2
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mongo
  endpoints:
    - port: mongo-metrics
