apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mongo-pod-monitor
  namespace: mongodb
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mongo-metrics
  podMetricsEndpoints:
    - port: mongo-metrics
