apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gamelogic-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2 # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gamelogic
  behaviour:
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleDown:
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: Utilization
        averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target: Utilization
        averageUtilization: 70
