apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalon-emailhandler
  labels:
    app: avalon-emailhandler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avalon-emailhandler
  template:
    metadata:
      labels:
        app: avalon-emailhandler
    spec:
      containers:
        - name: avalon-emailhandler
          image: blu3berrywhy/avalon-emailhandler:v1
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: avalon-secret
                  key: django-secret-key
            - name: APP_PASSWORD_EMAIL
              valueFrom:
                secretKeyRef:
                  name: avalon-secret
                  key: django-app-password
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: avalon-configmap
                  key: django-debug
            - name: EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: avalon-configmap
                  key: django-email-address
            - name: CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
            - name: KTOR_APP
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: ktor-app
---
apiVersion: v1
kind: Service
metadata:
  name: avalon-emailhandler
spec:
  selector:
    app: avalon-emailhandler
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
