apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamelogic
  labels:
    app: gamelogic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gamelogic
  template:
    metadata:
      labels:
        app: gamelogic
    spec:
      containers:
        - name: gamelogic
          image: blu3berrywhy/avalon-gamelogic
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: gamelogic
spec:
  selector:
    app: gamelogic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
