apiVersion: v1
kind: Secret
metadata:
  namespace: {{default "staging" .Release.Namespace}}
  name: {{.Values.name}}
type: Opaque
data:
  django-secret-key: {{.Values.secret.key}}
  django-app-password: {{.Values.secret.password}}
