apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{default "staging" .Release.Namespace}}
  name: {{.Values.name}}
data:
  django-email-address: {{.Values.config.email}}
  django-debug: "1"
  host: {{.Values.config.host}}
