apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{default "staging" .Release.Namespace}}
  name: {{.Values.name}}
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2 # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.name}}
  targetCPUUtilizationPercentage: 50 # target CPU utilization
