apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
        - name: {{.Values.name}}
          image: {{.Values.deployment.registry}}/{{.Values.deployment.image}}:{{.Values.deployment.tag}}
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.Values.name}}
                  key: django-secret-key
            - name: APP_PASSWORD_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{.Values.name}}
                  key: django-app-password
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.name}}
                  key: django-debug
            - name: EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.name}}
                  key: django-email-address
            - name: CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
            - name: KTOR_APP
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: ktor-app
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  selector:
    app: {{.Values.name}}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
