---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-50"
  name: {{.Values.monitoring.namespace}}
  labels:
    release: prometheus
