apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mongoReplicaset.name}}-metrics
  namespace: {{.Values.mongoReplicaset.namespace}}
  labels:
    app: mongodb-svc
spec:
  selector:
    app: mongodb-svc
  type: ClusterIP
  ports:
    - name: mongo-metrics
      protocol: TCP
      port: 9216
      targetPort: 9216