name: avalon-ingress

services:
  email_service:
    name: avalon-email-handler
    port: 80
    prefix: /playground
  gamelogic_service:
    name: gamelogic
    port: 80
    prefix: /

dependencies:
  gamelogic:
    enabled: true
  email:
    enabled: true
  traefik:
    enabled: true

email-handler:
  name: avalon-email-handler

  deployment:
    image: "avalon-emailhandler"
    registry: "blu3berrywhy"
    tag: "v1"

  config:
    email: "avalon.f.pass@gmail.com"
    host: "51.138.34.116"

  secret:
    key: "ZGphbmdvLWluc2VjdXJlLWg0dCRkXndibzU3XzM5XzZlY3ZtcW55YTFuI2ltKHYtKjgreGckJHQhKzlqXkAtcGQm"
    password: "bnZraHJ1Zmlwc2RxYXBvcA=="

gamelogic:
  deployment:
    image: "avalon-gamelogic"
    registry: "blu3berrywhy"
    tag: "v1.0.1"
    containerPort: 8080

  name: "gamelogic"
