apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalon-emailhandler
  labels:
    app: avalon-emailhandler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avalon-emailhandler
  template:
    metadata:
      labels:
        app: avalon-emailhandler
    spec:
      containers:
        - name: avalon-emailhandler
          image: blu3berrywhy/avalon-emailhandler
          ports:
            - containerPort: 8000
           env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: avalon-email-secret
                  key: secret-key
            - name: APP_PASSWORD_EMAIL
              valueFrom:
                secretKeyRef:
                  name: avalon-email-secret
                  key: app-password
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: avalon-email-configmap
                  key: debug
            - name: EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: avalon-email-configmap
                  key: email-address