apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongoset
spec:
  selector:
    matchLabels:
      app: mongo # has to match .spec.template.metadata.labels
  serviceName: "mongo"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mongo # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
        - name: mongo-exporter
          image: bitnami/mongodb-exporter:latest
          ports:
            - containerPort: 9216
              name: mongo-metrics
          args:
            [
              "--mongodb.uri=mongodb://127.0.0.1:27017/",
              "--web.listen-address=:9216",
            ]
  #           - --web.listen-address=:9216

  #serviceMonitor:
  #  additionalLabels:
  #    release: prometheus

  #       volumeMounts:
  #          - name: database
  #            mountPath: /data
  #
  #
  #  volumeClaimTemplates:
  #    - metadata:
  #        name: database
  #      spec:
  #        accessModes:
  #          - ReadWriteOnce
  #        #storageClassName: "local-storage"
  #        resources:
  #          requests:
  #            storage: 50Mi

  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
