apiVersion: apps/v1
kind: Deployment
metadata:
  #  namespace: forward-auth
  name: forward-auth
  labels:
    app: forward-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forward-auth
  template:
    metadata:
      labels:
        app: forward-auth
    spec:
      containers:
        - name: forward-auth
          image: blu3berrywhy/avalon-forwardauth:v1.0.6
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: forward-auth
                  key: secret
            - name: CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
