apiVersion: apps/v1
kind: Deployment
metadata:
  #  namespace: forward-auth
  name: forward-auth
  labels:
    app: forward-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forward-auth
  template:
    metadata:
      labels:
        app: forward-auth
    spec:
      containers:
        - name: forward-auth
          image: flask
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: forward-auth
                  key: secret
