# This is a basic workflow to help you get started with Actions

name: Build and push the latest build to staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_push_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0
        
      - name: test
        run: |
          ls
        
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push gamelogic
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./GameLogic
          push: true
          tags: ${{secrets.ACR_NAME}}/gamelogic:latest

      - name: Build and push email-handler
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./EmailHandlerAvalon
          push: true
          tags: ${{secrets.ACR_NAME}}/email-handler:latest
       
  deploy:
  
    runs-on: ubuntu-latest
    needs: build_push_image
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Helm tool installer
        uses: Azure/setup-helm@v2.0
        
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1.1
        with:
          # Resource Group Name
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          # AKS Cluster Name
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          # AKS Cluster Subscription
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Helm deploy
        run: |
         cd ./helm/avalon ;
         helm dependency build ;
         helm upgrade \
            --install \
            --create-namespace \
            --namespace staging \
            avalon \
            . \
            --set email-handler.deployment.registry=${{ secrets.ACR_NAME }} \
            --set gamelogic.deployment.registry=${{ secrets.ACR_NAME }} \
            --set email-handler.deployment.image=email-handler \
            --set gamelogic.deployment.image=gamelogic 
#            --atomic \
#            --wait \
      
